openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks with user isolation and JWT authentication.

paths:
  /api/{user_id}/tasks:
    get:
      summary: List tasks for user
      description: Returns all tasks owned by the authenticated user.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of tasks
        '401':
          description: Unauthorized - Token missing or invalid
        '403':
          description: Forbidden - User ID mismatch
    post:
      summary: Create task
      description: Creates a new task for the authenticated user.
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title: {type: string}
                description: {type: string}
      responses:
        '201':
          description: Task created
        '401':
          description: Unauthorized
        '422':
          description: Validation Error

  /api/{user_id}/tasks/{id}:
    parameters:
      - name: user_id
        in: path
        required: true
      - name: id
        in: path
        required: true
        schema: {type: string, format: uuid}
    get:
      summary: Get task details
      responses:
        '200': {description: Task details}
        '404': {description: Task not found}
    put:
      summary: Update task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: {type: string}
                description: {type: string}
                is_completed: {type: bool}
      responses:
        '200': {description: Task updated}
        '404': {description: Task not found}
    delete:
      summary: Delete task
      responses:
        '204': {description: Task deleted}
        '404': {description: Task not found}

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion
      parameters:
        - name: user_id
          in: path
          required: true
        - name: id
          in: path
          required: true
          schema: {type: string, format: uuid}
      responses:
        '200': {description: Task completion toggled}
        '404': {description: Task not found}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
